-- 1. User: backend_dev -> CRUD semua tabel
CREATE ROLE backend_dev WITH LOGIN PASSWORD 'backend_pass';
GRANT CONNECT ON DATABASE postgres TO backend_dev;
GRANT USAGE ON SCHEMA SALAM TO backend_dev;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA SALAM TO backend_dev;
ALTER DEFAULT PRIVILEGES IN SCHEMA SALAM
  GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO backend_dev;

-- 2. User: bi_dev -> hanya SELECT (read-only)
CREATE ROLE bi_dev WITH LOGIN PASSWORD 'bi_pass';
GRANT CONNECT ON DATABASE postgres TO bi_dev;
GRANT USAGE ON SCHEMA SALAM TO bi_dev;
GRANT SELECT ON ALL TABLES IN SCHEMA SALAM TO bi_dev;
ALTER DEFAULT PRIVILEGES IN SCHEMA SALAM
  GRANT SELECT ON TABLES TO bi_dev;

-- 3. User: data_engineer -> CREATE, MODIFY, DROP semua objek, CRUD semua tabel
CREATE ROLE data_engineer WITH LOGIN PASSWORD 'dataeng_pass';
GRANT CONNECT ON DATABASE postgres TO data_engineer;
GRANT USAGE ON SCHEMA SALAM TO data_engineer;
GRANT CREATE ON SCHEMA SALAM TO data_engineer;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA SALAM TO data_engineer;
ALTER DEFAULT PRIVILEGES IN SCHEMA SALAM
  GRANT ALL ON TABLES TO data_engineer;
